ProyectoDjangoV2/ProyectoDjango/ProyectoDjango/venv_proyecto/ProyectoAcademia/ProyectoAcademia/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('admin/', admin.site.urls),
    path('servicios/', include('servicios.urls')),
    path('blog/', include('blog.urls')),
    path('contacto/', include('contacto.urls')),
    path('cursos/', include('cursos.urls')),
    path('registro/', include('registro.urls')),
    path('autenticacion/', include('autenticacion.urls')),
    path('asignacion/', include('asignacion.urls')),
    path('usuario/', include('usuario.urls')),
    path('', include('AcademiaApp.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ProyectoDjangoV2/ProyectoDjango/ProyectoDjango/venv_proyecto/ProyectoAcademia/blog/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('',views.blog, name="Blog"),
    path('categoria/<int:categoria_id>/',views.categoria, name="categoria"),
]

ProyectoDjangoV2/ProyectoDjango/ProyectoDjango/venv_proyecto/ProyectoAcademia/usuario/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.usuario, name="Usuario_Seleccionado"),
]

ProyectoDjangoV2/ProyectoDjango/ProyectoDjango/venv_proyecto/ProyectoAcademia/cursos/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator
from django.utils import timezone

class AreaCurso(models.Model):
    nombre=models.CharField(max_length=50)
    created=models.DateField(auto_now_add=True)
    updated=models.DateField(auto_now_add=True)

    class Meta:
        verbose_name="areaCurso"
        verbose_name_plural="areasCursos"

    def __str__(self):
        return self.nombre
    
class Curso(models.Model):
    nombre=models.CharField(max_length=50)
    descripcion=models.CharField(max_length=255)
    area=models.ForeignKey(AreaCurso, on_delete=models.CASCADE)
    imagen=models.ImageField(upload_to="cursos", null=True, blank=True)
    precio=models.FloatField(validators=[MinValueValidator(0.0)])
    alumnos = models.ManyToManyField(User, through='AsignacionAlumnoCurso')
    disponibilidad=models.BooleanField(default=True)
    created=models.DateField(auto_now_add=True)
    updated=models.DateField(auto_now_add=True)

    class Meta:
        verbose_name="Curso"
        verbose_name_plural="Cursos"

    def __str__(self):
        return self.nombre
    
class AsignacionAlumnoCurso(models.Model):
    nombre_alumno=models.CharField(max_length=50, default='default')
    nombre_curso=models.CharField(max_length=50, default='default')
    nota=models.FloatField(default=0.0)
    alumno = models.ForeignKey(User, on_delete=models.CASCADE)
    curso = models.ForeignKey(Curso, on_delete=models.CASCADE)
    fecha_asignacion = models.DateField(auto_now_add=True)
    created=models.DateField(default=timezone.now)
    updated=models.DateField(default=timezone.now)

    class Meta:
        unique_together = ('alumno', 'curso') 
        verbose_name="Asignación curso"
        verbose_name_plural="Asignaciones cursos"

    def __str__(self):
        return f"{self.alumno.username} asignado a {self.curso.nombre}"

ProyectoDjangoV2/ProyectoDjango/ProyectoDjango/venv_proyecto/ProyectoAcademia/usuario/models.py
from django.db import models
from django.contrib.auth.models import User

class UsuarioAlumno(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, default=1)
    nombre=models.CharField(max_length=50)
    apellido=models.CharField(max_length=50)
    dpi=models.IntegerField()
    fecha_nacimiento=models.CharField(max_length=10)
    telefono=models.IntegerField()
    email=models.EmailField(default="example@example.com")
    imagen=models.ImageField(upload_to="alumnos", null=True, blank=True)
    created=models.DateField(auto_now_add=True)
    updated=models.DateField(auto_now_add=True)

    class Meta:
        verbose_name="Usuario Alumno"
        verbose_name_plural="Usuarios Alumnos"

    def __str__(self):
        return self.nombre
        
    
class UsuarioProfesor(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, default=1)
    username=models.CharField(max_length=50)
    nombre=models.CharField(max_length=50)
    apellido=models.CharField(max_length=50)
    dpi=models.IntegerField()
    imagen=models.ImageField(upload_to="profesores", null=True, blank=True)
    created=models.DateField(auto_now_add=True)
    updated=models.DateField(auto_now_add=True)

    class Meta:
        verbose_name="Usuario Profesor"
        verbose_name_plural="Usuarios Profesores"

    def __str__(self):
        return self.username

ProyectoDjangoV2/ProyectoDjango/ProyectoDjango/venv_proyecto/ProyectoAcademia/usuario/views.py
from django.shortcuts import render
from .models import UsuarioAlumno, UsuarioProfesor
from cursos.models import AsignacionAlumnoCurso, Curso

def usuario(request):

    usuario = request.user 
    datos_usuario = usuario.usuarioalumno
    asignaciones = AsignacionAlumnoCurso.objects.filter(alumno=usuario)
    cursos_asignados = [asignacion.curso for asignacion in asignaciones]
    
    return render(request,"usuario/usuario.html", {"cursos_asignados": cursos_asignados, "datos_usuario": datos_usuario, "asignaciones": asignaciones})

ProyectoDjangoV2/ProyectoDjango/ProyectoDjango/venv_proyecto/ProyectoAcademia/usuario/templates/usuario/usuario.html
{% extends "AcademiaApp/base.html" %}

{% load static %}

{% block content %}
<style>
        .tarjeta-usuario {
            background: linear-gradient(to right, #e74a01, #FFD700); 
            border: 1px solid #ddd;
            border-radius: 10px;
            padding: 20px;
            display: flex;
            flex-direction: column;
            align-items: center;
            text-align: center;
        }

        .imagen-perfil {
            max-width: 150px;
            max-height: 150px;
            border-radius: 50%;
            margin: 10px 0;
        }

        .cursos-asignados {
            margin-top: 20px;
        }
</style>
<div class="tarjeta-usuario">
    <img src="{{ datos_usuario.imagen.url }}" alt="Foto de perfil de {{ datos_usuario.nombre }}" class="imagen-perfil">

    <h2>{{ datos_usuario.nombre }} {{ datos_usuario.apellido }}</h2>
    <p><strong>DPI:</strong> {{ datos_usuario.dpi }}</p>
    <p><strong>Fecha de Nacimiento:</strong> {{ datos_usuario.fecha_nacimiento }}</p>
    <p><strong>Teléfono:</strong> {{ datos_usuario.telefono }}</p>
    <p><strong>Email:</strong> {{ datos_usuario.email }}</p>
</div>

<div class="container">
    <div class="row">
        {% for curso in cursos_asignados %}
            <div class="col-md-3">
                <div class="card" style="width: 100%; margin: 20px 20px;">
                    <a href="{% url 'Seleccionado' curso.id %}"><img src="{{curso.imagen.url}}" class="card-img-top"></a>
                    <a href="{% url 'Seleccionado' curso.id %}" style="color: rgb(48, 44, 44);"><div class="card-body" style="text-align: center;">
                        <h7 class="card-title"><b>{{curso.nombre}}</h7></b><br>
                        <h7 class="card-title">{{curso.descripcion}}</h7><br><br>
                        <p class="card-title">Q&nbsp;{{curso.precio}}</p>
                    </div></a>
                    <div class="card-footer text-center" >
                        <a style="margin: 0px 0px 0px -10px; color: black;">Su nota actual es:
                        {% for asignacion in curso.asignacionalumnocurso_set.all %}
                            {% if asignacion.alumno == user %}
                                {{ asignacion.nota }}
                            {% endif %}
                        {% endfor %}
                        </a>
                    </div>
                </div>
            </div>
        {% endfor%}
        <section>
            <div style="width: 75%; margin: 40px auto; text-align: center; color: gray;">
                <a href="{% url 'generar_certificado' %}" class="btn btn-primary">Generar Certificado</a>
            </div>
        </section>
    </div>
</div>
{% endblock %}